import pandas as pd

# Load the provided Excel file
file_path = '昆虫.xlsx'
df_insects = pd.read_excel(file_path)

# Rename columns for easier access
df_insects.columns = ['Species', 'Order']

# Updated species to order mapping dictionary
species_to_order = {
    'silkworm': 'Lepidoptera',
    'Trypoxylus dichotomus': 'Coleoptera',
    'honeybee': 'Hymenoptera',
    'Gryllus bimaculatus': 'Orthoptera',
    'yellow mealworm': 'Coleoptera',
    'Tenebrio molitor': 'Coleoptera',
    'American cockroach': 'Blattodea',
    'Aedes albopictus': 'Diptera',
    'housefly': 'Diptera',
    'housefly larvae': 'Diptera',
    'Drosophila melanogaster': 'Diptera',
    'Dung beetle': 'Coleoptera',
    'Dendroctonus': 'Coleoptera',
    'Apis mellifera': 'Hymenoptera',
    'Aquatica leii': 'Coleoptera',
    'Hermetia illucens': 'Diptera',
    'Drosophila': 'Diptera',
    'Aphids': 'Hemiptera',
    'Black soldier fly larvae': 'Diptera',
    'Huhu grubs': 'Coleoptera',
    'Honeybee': 'Hymenoptera',
    'Yellow mealworm (Tenebrio molitor, Coleoptera: Tenebrionidae) larvae': 'Coleoptera',
    'Periplaneta americana': 'Blattodea',
    'Musca domestica': 'Diptera',
    'Beetle': 'Coleoptera',
    'True Bug': 'Hemiptera',
    'Hog lice': 'Phthiraptera',
    'Zeuzera coffeae': 'Lepidoptera',
    'Bumblebee': 'Hymenoptera',
    'Pachnoda marginata': 'Coleoptera',
    'Dorcus hopei': 'Coleoptera',
    'Blattella germanica': 'Blattodea',
    'Sterile medfly': 'Diptera',
    'Scyphophorus acupunctatus': 'Coleoptera',
    'Protaetia acuminata': 'Coleoptera',
    'Mosquito': 'Diptera',
    'Harmonia axyridis': 'Coleoptera',
    'Bactrocera dorsalis': 'Diptera',
    'Locusta migratoria': 'Orthoptera',
    'Bathycoelia distincta': 'Hemiptera',
    'Tea Moth': 'Lepidoptera',
    'Galleria mellonella': 'Lepidoptera',
    'Drosophila melanogaster': 'Diptera',
    'Tenebrio molitor L.': 'Coleoptera',
    'Stink Bug': 'Hemiptera',
    'Musca domestica larvae': 'Diptera',
    'Cnaphalocrocis medinalis': 'Lepidoptera',
    'Bombus terrestris': 'Hymenoptera',
    'Spodoptera exigua': 'Lepidoptera',
    'Spodoptera frugiperda': 'Lepidoptera',
    'Apis mellifera Ligustica Spinola': 'Hymenoptera',
    'Sarcophaga peregrina': 'Diptera',
    'Ctenocephalides felis': 'Siphonaptera',
    'Diaphorina citri Kuwayama': 'Hemiptera',
    'Cotinis nitida': 'Coleoptera',
    'Spodoptera littoralis': 'Lepidoptera',
    'Aphis gossypii Glover': 'Hemiptera',
    'Vespa velutina': 'Hymenoptera',
    'Medfly': 'Diptera',
    'Spodoptera frugiperda': 'Lepidoptera',
    'Clanis bilineata tsingtauica': 'Lepidoptera',
    'Pantala flavescens': 'Odonata',
    'Euschistus heros': 'Hemiptera',
    'Bombyx mori': 'Lepidoptera',
    'Ensifera': 'Orthoptera',
    'Spodoptera litura': 'Lepidoptera',
    'Bemisia tabaci': 'Hemiptera',
    'Blowflies': 'Diptera',
    'Apis cerana': 'Hymenoptera',
    'Glossina palpalis': 'Diptera',
    'Termite': 'Blattodea',
    'Diatraea saccharalis': 'Lepidoptera',
    'Drosophila melanogaster': 'Diptera',
    'Pieris brassicae': 'Lepidoptera',
    'Locust': 'Orthoptera',
    'Tephritid': 'Diptera',
    'Grapholita molesta': 'Lepidoptera',
    'Nilaparvata lugens': 'Hemiptera',
    'Blattella germanica (L.)': 'Blattodea',
    'Triatomines': 'Hemiptera',
    'Ant': 'Hymenoptera',
    'Cyrtotrachelus buqueti': 'Coleoptera',
    'Pelidnota luridipes': 'Coleoptera',
    'Dysdercus cingulatus': 'Hemiptera',
    'Dysdercus': 'Hemiptera',
    'Lepidoptera': 'Lepidoptera',
    'Drosophila': 'Diptera',
    'Bumble bee': 'Hymenoptera',
    'Bactrocera minax': 'Diptera',
    'Zeuzera coffeae': 'Lepidoptera',
    'Sirex noctilio': 'Hymenoptera',
    'Plutella xylostella': 'Lepidoptera',
    'Lucilla sericata': 'Diptera',
    'Rhynchophorus ferrugineus': 'Coleoptera',
    'Spodoptera': 'Lepidoptera',
    'Vespa': 'Hymenoptera',
    'Blattella': 'Blattodea',
    'Culex': 'Diptera',
    'Anopheles': 'Diptera',
    'Pieris': 'Lepidoptera',
    'Agrotis': 'Lepidoptera',
    'Tabanus': 'Diptera',
    'Anthonomus': 'Coleoptera',
    'Curculio': 'Coleoptera',
    'Bactrocera': 'Diptera',
    'Papaya Mealybug': 'Hemiptera',
    'Pterostichus': 'Coleoptera',
    'Philornis': 'Diptera',
    'Tephritid fruit fly': 'Diptera',
    'Ambrostoma': 'Coleoptera',
    'Sarcophagidae': 'Diptera',
    'Aedes': 'Diptera',
    'Protaetia': 'Coleoptera',
    'Megachile': 'Hymenoptera',
    'Odonata': 'Odonata',
    'Lycaenidae': 'Lepidoptera',
    'Odontotermes': 'Blattodea',
    'Cimex': 'Hemiptera',
    'Callosobruchus': 'Coleoptera',
    'Coptotermes': 'Blattodea',
    'Bemisia': 'Hemiptera',
    'Leptopilina': 'Hymenoptera',
    'Scyphophorus': 'Coleoptera',
    'Ctenocephalides': 'Siphonaptera',
    'Xylophagous': 'Blattodea',
    'Nicrophorus': 'Coleoptera',
    'Sirex': 'Hymenoptera',
    'Cephalotes': 'Hymenoptera',
    'Tetragonula': 'Hymenoptera',
    'Wiseana': 'Lepidoptera',
    # Continue to add more species to order mappings as needed
}

# Map the species to their orders
df_insects['Order'] = df_insects['Species'].map(species_to_order)


# Save the updated dataframe back to an Excel file
output_file_path = 'Updated_昆虫.xlsx'
df_insects.to_excel(output_file_path, index=False)


